# Generated by Django 5.1 on 2024-11-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='Id_Compra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
